Repository ogniloud/MADR, pull requests merged in 2024-05, with the labels that each got.

#146 madr.org title to madr.space
  madr_web_app/public/index.html
  madr_web_app/src/App Components/User-Components/SignIn.js
  madr_web_app/src/App Components/User-Components/SignUp.js
  madr_web_app/src/App Components/User-Components/User-Components-Style/SignIn.css
  madr_web_app/src/App Components/User-Components/User-Components-Style/SignUp.css
Labels: bug

#147 run go tests in ci
  Dockerfile
Labels: enhancement

#150 update go version and libraries
  Dockerfile
  go.mod
  go.sum
Labels: Backend

#153 add link to our site
  README.md
Labels: documentation

#129 Bug Fixing
  madr_web_app/src/App Components/Page-Components/Decks/Browse Cards/AllWords.js
  madr_web_app/src/App Components/Page-Components/Decks/Exercise Cards/WordMatch.js
  madr_web_app/src/App Components/Page-Components/Drawer-Components/Drawer.js
  madr_web_app/src/App Components/Page-Components/Drawer-Components/Styles/Drawer.css
  madr_web_app/src/App Components/Page-Components/MainPage.js
  madr_web_app/src/App Components/Page-Components/Styles/MainPage.css
  madr_web_app/src/App Components/User-Components/ConfirmationDialog.js
  madr_web_app/src/App Components/User-Components/SignUp.js
Labels: bug

#170 [Bug Fixed and updateded ]: carousels,navigation,layer
  cmd/api-server/main.go
  madr_web_app/package-lock.json
  madr_web_app/package.json
  madr_web_app/src/App Components/Page-Components/Decks/Browse Cards/AllWords.js
  madr_web_app/src/App Components/Page-Components/Decks/CreateDecks.js
  madr_web_app/src/App Components/Page-Components/Decks/DeckDetail.js
  madr_web_app/src/App Components/Page-Components/Decks/DeckPage.js
  madr_web_app/src/App Components/Page-Components/Decks/Exercise Cards/Flashcards.js
  madr_web_app/src/App Components/Page-Components/Decks/Exercise Cards/Styles/Flashcards.css
  madr_web_app/src/App Components/Page-Components/Decks/Exercise Cards/Styles/WordMatch.css
  madr_web_app/src/App Components/Page-Components/Decks/Exercise Cards/WordMatch.js
  madr_web_app/src/App Components/Page-Components/Decks/Styles/CreateDecks.css
  madr_web_app/src/App Components/Page-Components/Decks/Styles/DeckDetails.css
  madr_web_app/src/App Components/Page-Components/Decks/Styles/DeckPage.css
  madr_web_app/src/App Components/Page-Components/Drawer-Components/Drawer.js
  madr_web_app/src/App Components/Page-Components/Feeds/FeedPage.css
  madr_web_app/src/App Components/Page-Components/Feeds/FeedsPage.js
  madr_web_app/src/App Components/Page-Components/Styles/MainPage.css
Labels: bug, Frontend
